" pathogen settings
"let g:python_host_prog = '/usr/local/bin/python2.7'
execute pathogen#infect()

" general settings
syntax on
set cursorline
set number
syntax enable
filetype plugin indent on
set laststatus=2
set hlsearch
set clipboard=unnamed
let python_highlight_all=1

" tab settings
au BufNewFile,BufRead *.py
    \ set tabstop=8 |
    \ set shiftwidth=4 |
    \ set softtabstop=4 |
    \ set expandtab |
    \ set autoindent |
    \ set smartindent |
au BufNewFile,BufRead *.js, *.html, *.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |

" encoding settings
set encoding=utf-8
set fileencodings=iso-2022-jp,cp932,sjis,euc-jp,utf-8

" colorscheme settings
set background=dark
set term=xterm-256color
let g:solarized_termcolors=256
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
colorscheme lucius

set foldmethod=marker

" powerline settings
" python from powerline.vim import setup as powerline_setup
" python powerline_setup()
" python del powerline_setup

" spell check settings
au BufNewFile,BufRead *.tex
    \ setlocal spell |
    \ setlocal spell spelllang=en_us |
au BufNewFile,BufRead *.txt
    \ setlocal spell |
    \ setlocal spell spelllang=en_us |
hi clear SpellBad 
hi SpellBad cterm=underline,bold ctermfg=red

" airline settings
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline_theme='cool'
let g:airline_powerline_fonts = 0
let NERDTreeIgnore=['\.pyc$', '\~$', '\.aux$', '\.bbl$', '\.blg$', '\.dvi$', '\.lof$', '\.log$', '\.pdf$', '\.toc$', '\.lot$'] "ignore files in NERDTree

" make backspaces more powerfull
set backspace=indent,eol,start

" js stuff
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2

" python stuff 
autocmd FileType python set omnifunc=pythoncomplete#Complete

" syntastic settings 
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
